package com.automic.roomdemo.baseparts.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.automic.roomdemo.buworkroom.bean.EmployeesWorkStation;

import com.automic.roomdemo.baseparts.dao.EmployeesWorkStationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig employeesWorkStationDaoConfig;

    private final EmployeesWorkStationDao employeesWorkStationDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        employeesWorkStationDaoConfig = daoConfigMap.get(EmployeesWorkStationDao.class).clone();
        employeesWorkStationDaoConfig.initIdentityScope(type);

        employeesWorkStationDao = new EmployeesWorkStationDao(employeesWorkStationDaoConfig, this);

        registerDao(EmployeesWorkStation.class, employeesWorkStationDao);
    }
    
    public void clear() {
        employeesWorkStationDaoConfig.clearIdentityScope();
    }

    public EmployeesWorkStationDao getEmployeesWorkStationDao() {
        return employeesWorkStationDao;
    }

}
